const tb = {};
tb.D0010Tpye = {
  'CUST_CODE': ['varchar(10)'],
  'CUSTOMER_NAME': ['varchar(100)'],
  'ABBR_NAME': ['varchar(10)'],
  'BILLING_ADDRESS_1': ['varchar(100)'],
  'BILLING_ADDRESS_2': ['varchar(50)'],
  'BILLING_ADDRESS_3': ['varchar(30)'],
  'STATE': ['varchar(10)'],
  'ZIP': ['char(10)'],
  'PHONE': ['char(20)'],
  'FAX': ['char(20)'],
  'TELEX': ['varchar(50)'],
  'SALES_REP_PTR': ['int'],
  'CURRENCY_PTR': ['int'],
  'INVOICE_NOTE_PAD_PTR': ['int', 0],
  'CONTACT_NAME_1': ['char(20)'],
  'CONTACT_NAME_2': ['char(20)'],
  'CONTACT_NAME_3': ['char(20)'],
  'CONTACT_NAME_4': ['char(20)'],
  'CONTACT_NAME_5': ['char(20)'],
  'CONTACT_NAME_6': ['char(20)'],
  'CONT_PHONE_1': ['char(14)'],
  'CONT_PHONE_2': ['char(14)'],
  'CONT_PHONE_3': ['char(14)'],
  'CONT_PHONE_4': ['char(14)'],
  'CONT_PHONE_5': ['char(14)'],
  'CONT_PHONE_6': ['char(14)'],
  'FED_TAX_ID_NO': ['varchar(50)'],
  'COFC_FILENAME': ['char(15)', 'N'],
  'COD_FLAG': ['char(1)', 'N'],
  'REG_TAX_FIXED_UNUSED': ['char(1)', 0],
  'DISCOUNT_PCT': ['decimal(5)', 0],
  'HIGH_BALANCE': ['float(8)', 0],
  'CREDIT_LIMIT': ['float(8)'],
  'CREDIT_RATING': ['tinyint'],
  'BALANCE_DUE': ['float(8)', 0],
  'OUTSTANDING_CREDIT': ['float(8)', 0],
  'DISCOUNT_DAYS': ['smallint', 0],
  'CURRENT_BOOKINGS': ['float(8)', 0],
  'NET_PAY': ['smallint'],
  'LAST_ACTIVE_DATE': ['smalldatetime'],
  'LANGUAGE_FLAG': ['char(1)'],
  'BILLING_ADDRESS_4': ['varchar(100)'],
  'COUNTRY_PTR': ['int'],
  'INTERNAL_ECN_COUNT': ['smallint', 0],
  'EXTERNAL_ECN_COUNT': ['smallint', 0],
  'OUTGOING_FORM_NAME': ['varchar(50)'],
  'OUTGOING_FORM_ADDR1': ['varchar(70)'],
  'OUTGOING_FORM_ADDR2': ['varchar(45)'],
  'OUTGOING_FORM_ADDR3': ['varchar(45)'],
  'ANALYSIS_CODE1': ['varchar(20)'],
  'ANALYSIS_CODE2': ['varchar(20)'],
  'ANALYSIS_CODE3': ['varchar(20)'],
  'CUST_ENT_DATE': ['smalldatetime'],
  'EDI_ID': ['varchar(50)'],
  'EDI_FLAG_FOR_SOACK': ['smallint'],
  'EDI_FLAG_FOR_INVOICE': ['smallint'],
  'EDI_FLAG_CREDIT_MEMO': ['smallint'],
  'GEN_EMAIL_ADDRESS': ['char(50)'],
  'EMAIL_FOR_CONTACT1': ['char(50)'],
  'EMAIL_FOR_CONTACT2': ['char(50)'],
  'EMAIL_FOR_CONTACT3': ['char(50)'],
  'EMAIL_FOR_CONTACT4': ['char(50)'],
  'EMAIL_FOR_CONTACT5': ['char(50)'],
  'EMAIL_FOR_CONTACT6': ['char(50)'],
  'ACC_REC_PTR': ['int'],
  'CONSUME_FORECASTS': ['tinyint', 0],
  'BACKWARD_DAYS': ['int', 0],
  'FORWARD_DAYS': ['int', 0],
  'PLANNING_HORIZON': ['int', 0],
  'RAW_HORIZON': ['int', 0],
  'VISIBILITY_HORIZON': ['int', 0],
  'DAYS_EARLY_SCHEDULE': ['int', 0],
  'APPLY_IN_TRANSIT': ['tinyint', 0],
  'CUSTOMER_TYPE': ['int'],
  'DO_SMOOTHING': ['tinyint', 0],
  'SMOOTHING_THRESHOLD': ['int'],
  'ANALYSIS_CODE4': ['varchar(20)'],
  'ANALYSIS_CODE5': ['varchar(20)'],
  'EDI_IN_LOGGING': ['tinyint'],
  'quote_factor': ['float(8)', 0],
  'QUOTE_FACTOR1': ['float(8)', 0],
  'REP_EVAL': ['varchar(70)'],
  'MAK_EVAL': ['varchar(70)'],
  'FIN_EVAL': ['varchar(70)'],
  'MARMANG_EVAL': ['varchar(70)'],
  'REP_CREDIT': ['float(8)'],
  'MAK_CREDIT': ['float(8)'],
  'FIN_CREDIT': ['float(8)'],
  'MARMANG_CREDIT': ['float(8)'],
  'REP_HIGH': ['float(8)'],
  'MAK_HIGH': ['float(8)'],
  'FIN_HIGH': ['float(8)'],
  'MARMANG_HIGH': ['float(8)'],
  'REP_NAME': ['varchar(16)'],
  'MAK_NAME': ['varchar(16)'],
  'FIN_NAME': ['varchar(16)'],
  'MARMANG_NAME': ['varchar(16)'],
  'REP_DATE': ['smalldatetime'],
  'MAK_DATE': ['smalldatetime'],
  'FIN_DATE': ['smalldatetime'],
  'MARMANG_DATE': ['smalldatetime'],
  'HOUSE_FIXED': ['varchar(4)'],
  'FIXED_SCOPE': ['varchar(30)'],
  'SALES_DISCOUNT': ['decimal(5)'],
  'MONTH_AMOUNT': ['float(8)'],
  'MONTH_PCBAMOUNT': ['float(8)'],
  'CAPITAL': ['float(8)'],
  'INVOICE_TYPE': ['varchar(20)'],
  'quote_flag': ['bit', 0],
  'Remark': ['varchar(max)'],
  'RemarkSpec': ['varchar(max)'],
  // 'LAST_UPDT': ['datetime'],
  'CUSTOMER_GROUP': ['varchar(30)']

};
tb.D0010Must = [
  'CUST_CODE',
  'CUSTOMER_NAME',
  'ABBR_NAME',
  'CURRENCY_PTR',
  'INVOICE_NOTE_PAD_PTR',
  'COD_FLAG',
  'REG_TAX_FIXED_UNUSED',
  'CREDIT_LIMIT',
  'CREDIT_RATING',
  'NET_PAY',
  'CUST_ENT_DATE',
  'CONSUME_FORECASTS',
  'DO_SMOOTHING',
  'SMOOTHING_THRESHOLD',
  'CUSTOMER_GROUP'
];
tb.D0012Tpye = {
  'CUSTOMER_PTR': ['int'],
  'LOCATION': ['varchar(80)'],
  'SHIP_TO_ADDRESS_1': ['varchar(100)'],
  'SHIP_TO_ADDRESS_2': ['varchar(50)'],
  'SHIP_TO_ADDRESS_3': ['varchar(30)'],
  'STATE': ['varchar(10)'],
  'ZIP': ['varchar(10)'],
  'SHIP_TO_CONTACT': ['varchar(20)'],
  'SHIP_TO_PHONE': ['varchar(20)'],
  'SHIP_TO_FAX': ['varchar(20)'],
  'SREP_PTR_1': ['int'],
  'SREP_PTR_2': ['int'],
  'SREP_PTR_3': ['int'],
  'SREP_PTR_4': ['int'],
  'SREP_PTR_5': ['int'],
  'SREP_1_COMM': ['decimal(5)'],
  'SREP_2_COMM': ['decimal(5)'],
  'SREP_3_COMM': ['decimal(5)'],
  'SREP_4_COMM': ['decimal(5)'],
  'SREP_5_COMM': ['decimal(5)'],
  'SREP_1_ALLOC': ['decimal(5)'],
  'SREP_2_ALLOC': ['decimal(5)'],
  'SREP_3_ALLOC': ['decimal(5)'],
  'SREP_4_ALLOC': ['decimal(5)'],
  'SREP_5_ALLOC': ['decimal(5)'],
  'SHIP_CTAX_PTR': ['int'],
  'SHIP_SHIPPING_METHOD': ['varchar(20)', '汽运'],
  'SHIP_LEAD_TIME': ['smallint', 1],
  'SHIP_FOB': ['varchar(20)'],
  'SHIP_REG_TAX_ID': ['varchar(15)'],
  'STATE_SHIP_TAX_FLAG': ['char(1)', 'N'],
  'STATE_PROD_TAX_FLAG': ['char(1)', 'Y'],
  'STATE_TOOL_TAX_FLAG': ['char(1)', 'N'],
  'LANGUAGE_FLAG': ['char(1)'],
  'OVERSHIP_BY_QTY_1': ['float(53)', 0],
  'OVERSHIP_BY_QTY_2': ['float(53)', 0],
  'OVERSHIP_BY_QTY_3': ['float(53)', 0],
  'ORDER_QTY_RANGE_1': ['float(53)', 0],
  'ORDER_QTY_RANGE_2': ['float(53)', 0],
  'COUNTRY_PTR': ['int'],
  'LOCNAME_FOR_FORM': ['varchar(100)'],
  'SHP_ADDR1_FOR_FORM': ['varchar(100)'],
  'SHP_ADDR2_FOR_FORM': ['varchar(40)'],
  'SHP_ADDR3_FOR_FORM': ['varchar(40)'],
  'SHP_ANALYSIS_CODE1': ['varchar(20)'],
  'SHP_ANALYSIS_CODE2': ['varchar(20)'],
  'SHP_ANALYSIS_CODE3': ['varchar(20)'],
  'EMAIL_FOR_CONTACT': ['varchar(50)'],
  'DAYS_EARLY': ['int'],
  'DAYS_LATE': ['int'],
  'S4_BARCODE_LABLE': ['varchar(100)'],
  'S3_BARCODE_LABLE': ['varchar(100)'],
  'PACKGE_BARCODE_LABLE': ['varchar(100)'],
  'MISC_BARCODE_LABLE': ['varchar(100)'],
  'COFC_FORMAT_FILENAME': ['varchar(100)'],
  'overship_flag': ['tinyint'],
  'EXPIRED_DATE': ['smalldatetime']
};
tb.D0012Must = [
  'LOCATION',
  'SHIP_CTAX_PTR',
  'SHIP_LEAD_TIME',
];

module.exports = tb;
